In [23]:
# Show all output's on Jupyter Notebook
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [130]:
import numpy as np

sudoku_matrix = np.array([[5,3,0,0,7,0,0,0,0],
                    [6,0,0,1,9,5,0,0,0],
                    [0,9,8,0,0,0,0,6,0],
                    [8,0,0,0,6,0,0,0,3],
                    [4,0,0,8,0,3,0,0,1],
                    [7,0,0,0,2,0,0,0,6],
                    [0,6,0,0,0,0,2,8,0],
                    [0,0,0,4,1,9,0,0,5],
                    [0,0,0,0,8,0,0,0,0]]).reshape(9,9)

# First column and row
print(sudoku_matrix)
print('\n')


def condition_test(number, position_x, position_y):
    # First condition - Same row
    condition_1 = number in sudoku_matrix[position_x, :]
    # Second condition - Same column
    condition_2 = number in sudoku_matrix[:, position_y]
    # Third condition - Same 3x3 matrix
    condition_3 = number in sudoku_matrix[3*int(position_x/3) : 3+3*int(position_x/3) , 3*int(position_y/3) : 3+3*int(position_y/3)]
    # If True, then, the three conditions are valid
    return(not (condition_1 or condition_2 or condition_3))



def solve_sudoku(sudoku_matrix):
    for j in range(len(sudoku_matrix)):
        for i in range(len(sudoku_matrix)):
            if sudoku_matrix[j, i] == 0:
                for value in range(1, 10):
                    condition_satisfy = condition_test(value, j, i)                 
                    if condition_satisfy == True:
                        sudoku_matrix[j, i] = value
                        solve_sudoku(sudoku_matrix)
                        sudoku_matrix[j, i] = 0
                return  
    print('\n')
    print(sudoku_matrix)
                    
                        
                        
    
print('Possible solutions: ')
solve_sudoku(sudoku_matrix)

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 0 0]]


Possible solutions: 


[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]


[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
